# -*- coding: utf-8 -*-
"""TensorFlow_Weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G4t_6PVTD8uNMCSEVu9lZCyVH1cY6MwB
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x
import tensorflow as tf 
import tensorflow_probability as tfp

tfd = tfp.distributions
initial_distribution = tfd.Categorical(probs=[0.8,0.2])
trans_distribution = tfd.Categorical(probs=[[0.9,0.1],[0.2,0.8]])
observ_distribution = tfd.Normal(loc=[0., 15.], scale=[5.,10.])

model = tfd.HiddenMarkovModel(initial_distribution=initial_distribution, transition_distribution=trans_distribution, observation_distribution=observ_distribution,num_steps=14)

mean=model.mean()

with tf.compat.v1.Session() as se:
  print(mean.numpy())